export const ADD_CLIENT = 'ADD_CLIENT',
    UPDATE_CLIENT = 'UPDATE_CLIENT',
    REMOVE_CLIENT = 'REMOVE_CLIENT',
    GET_CLIENT = 'GET_CLIENT',
    SET_ORDENACAO = 'SET_ORDENACAO',
    SET_PESQUISA = 'SET_PESQUISA',
    SET_CLIENTE = 'SET_CLIENTE';
